# Generated by Django 5.0.3 on 2024-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='nombre_usuario',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='contraseña_encriptada',
            field=models.CharField(max_length=255),
        ),
    ]
