# Generated by Django 5.0.3 on 2024-05-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0003_usuarios_folder_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
