# Generated by Django 5.0.3 on 2024-05-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0005_remove_item_folder_grupo_delete_folder_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='miembros',
        ),
    ]
