# Generated by Django 5.0.3 on 2024-05-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0007_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='url',
        ),
        migrations.AddField(
            model_name='contenido',
            name='calidad_contraseña',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='contraseña',
            field=models.CharField(max_length=50),
        ),
    ]
