# Generated by Django 5.0.3 on 2024-05-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0008_remove_contenido_url_contenido_calidad_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='calidad_contraseña',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=5, null=True),
        ),
    ]
