# Generated by Django 5.0.3 on 2024-05-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0010_remove_contenido_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
