# Generated by Django 5.0.3 on 2024-05-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0011_alter_contenido_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='contraseña_encriptada',
        ),
        migrations.AddField(
            model_name='contenido',
            name='contraseña',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='calidad_contraseña',
            field=models.CharField(choices=[('N', 'Normal'), ('M', 'Medio'), ('F', 'Fuerte'), ('M-F', 'Muy Fuerte')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
