# Generated by Django 5.0.3 on 2024-05-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0012_remove_contenido_contraseña_encriptada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
