# Generated by Django 5.0.3 on 2024-05-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0013_alter_contenido_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='calidad_contraseña',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Medio', 'Medio'), ('Fuerte', 'Fuerte'), ('Muy Fuerte', 'Muy Fuerte')], default='N', max_length=10),
        ),
    ]
