# Generated by Django 5.0.3 on 2024-05-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0014_alter_contenido_calidad_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='calidad_contraseña',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Media', 'Media'), ('Fuerte', 'Fuerte'), ('Muy Fuerte', 'Muy Fuerte')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
