# Generated by Django 5.0.3 on 2024-05-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0015_alter_contenido_calidad_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='calidad_contraseña',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Media', 'Media'), ('Fuerte', 'Fuerte'), ('Muy Fuerte', 'Muy Fuerte')], default='N', max_length=10, null=True),
        ),
    ]
