# Generated by Django 5.0.3 on 2024-05-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0018_alter_contenido_calidad_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='calidad_contraseña',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Media', 'Media'), ('Fuerte', 'Fuerte'), ('Muy Fuerte', 'Muy Fuerte')], default='Normal', max_length=10),
        ),
    ]
