# Generated by Django 5.0.3 on 2024-05-10 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0020_alter_contenido_calidad_contraseña_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.AlterField(
            model_name='contenido',
            name='contraseña',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
