# Generated by Django 5.0.3 on 2024-05-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0021_delete_entrada_alter_contenido_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='conteido',
            field=models.ManyToManyField(to='nuestra_web.contenido'),
        ),
    ]
