# Generated by Django 5.0.3 on 2024-05-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuestra_web', '0022_grupo_conteido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='conteido',
            new_name='contenido_del_grupo',
        ),
    ]
